# events {
#     worker_connections 1024;
# }


upstream backend_services {
    # Passive health checks: 
    # If a server fails 3 times within 30 seconds, Nginx marks it as "down" 
    # and won't send traffic to it for 30 seconds.
    server user-service1:8001 max_fails=3 fail_timeout=30s;
    server user-service2:8001 max_fails=3 fail_timeout=30s;
}

server {
    listen 8000;
    server_name localhost;

    location / {
        proxy_pass http://backend_services;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Timeouts to ensure Nginx fails fast if a backend is hanging
        proxy_connect_timeout 5s;
        proxy_read_timeout 10s;
    }
}
